import {
  RocketLaunch,
  ChartLineUp,
  UsersThree,
  Confetti,
  InstagramLogo,
  LinkedinLogo,
  Code,
  Handshake,
  Megaphone,
  GraduationCap,
  Wallet,
  Trophy,
  CalendarCheck,
  ChalkboardTeacher,
  MicrophoneStage,
  Flask,
} from "@phosphor-icons/react/dist/ssr";
import type { Icon } from "@phosphor-icons/react/lib";

export const iconMap: Record<string, Icon> = {
  "rocket-launch": RocketLaunch,
  "chart-line-up": ChartLineUp,
  "users-three": UsersThree,
  confetti: Confetti,
  "instagram-logo": InstagramLogo,
  "linkedin-logo": LinkedinLogo,
  code: Code,
  handshake: Handshake,
  megaphone: Megaphone,
  "graduation-cap": GraduationCap,
  wallet: Wallet,
  trophy: Trophy,
  "calendar-check": CalendarCheck,
  "chalkboard-teacher": ChalkboardTeacher,
  "microphone-stage": MicrophoneStage,
  flask: Flask,
};
